### ISSUE TITLE
Страница списка услуг

### ISSUE THREAD

**Issue by foxhable** [aaccent/new-tech_layout#7]
- Замени `h2` на `h1`

https://github.com/aaccent/new-tech_layout/blob/af14351083005102399e8cec9743bbb368f75e86/src/pages/page-services.hbs#L22-L25

- Заголовки "Категория услуг" замени с `h3` на `h2`

https://github.com/aaccent/new-tech_layout/blob/af14351083005102399e8cec9743bbb368f75e86/src/pages/page-services.hbs#L40-L42

**Comment by EduardoAlparov** [comment]
Заменил

**Comment by foxhable** [comment]
"Категория услуг 2" тоже `h2`
