### ISSUE TITLE
Контент

### ISSUE THREAD

**Issue by foxhable** [aaccent/new-tech_layout#9]
На страницах "Услуга", "Партнеры" и "Партнерам" нужно убрать `article` из контента, КМы явно пропустят его и будут искать, почему у них контейнер не тот

**Comment by EduardoAlparov** [comment]
а они вообще в верстку заглядывают или так наудачу заполняют? 
поменял

**Comment by foxhable** [comment]
> а они вообще в верстку заглядывают или так наудачу заполняют?

Заглядывают, когда появляются проблемы. Они привыкли минимальное количество тэгов использовать. Как правило это низко уровневые специалисты, которые не всегда понимают как работает верстка даже на базовом уровне
